CREATE TABLE IF NOT EXISTS tb_risk_tier_config (
  category    VARCHAR(50) NOT NULL PRIMARY KEY,
  tier        ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'low',
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
