CREATE TABLE IF NOT EXISTS tb_category_form_schema (
  category    VARCHAR(50) NOT NULL PRIMARY KEY,
  fields      JSON NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
