-- The central aggregate (spec tasks 02/03 as amended for R1 — decisions
-- 134-142, plano-denuncia.md). Filename supersedes the spec's stale
-- `001_reports.sql` (amendment E8).
--
-- Position: lat/lng hold the EXACT submission position (decision 7); the
-- exact value NEVER leaves the API (decision 135) — public reads serve a
-- degraded position by risk tier (R2). Composite index backs the
-- bounding-box + haversine feed query.
--
-- Retention/freeze columns mirror tb_media (decisions 131/141): the case
-- freezes AS A WHOLE — report + timeline + media — via the panel flow
-- built in R3.

CREATE TABLE IF NOT EXISTS tb_report (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  -- Idempotency key generated by the app, one per report (decision 137):
  -- an offline-queue replay (decision 28) finds this row and returns it,
  -- never a duplicate.
  client_key          CHAR(36) NOT NULL UNIQUE,
  -- Two mandatory axes (decisions 3/140): category XOR free_tag on the
  -- first axis (decision 9's hybrid), subject always present ('other' is
  -- the one-tap fallback protecting decision 123).
  category            VARCHAR(50) NULL,
  free_tag            VARCHAR(50) NULL,
  subject             VARCHAR(50) NOT NULL,
  -- Validated server-side against the category's CategoryFormSchema
  -- (decision 47) before insert.
  detail_fields       JSON NULL,
  lat                 DECIMAL(9,6) NOT NULL,
  lng                 DECIMAL(9,6) NOT NULL,
  -- Anonymity is an explicit CHOICE (decision 32): a logged-in reporter
  -- may submit anonymously — the account id is then kept here internally
  -- only (forensic accountability, decision 23) and never exposed.
  anonymous           CHAR(1) NOT NULL DEFAULT 'N',
  reporter_account_id INT NULL,
  status              VARCHAR(10) NOT NULL DEFAULT 'open',
  resolved_at         DATETIME NULL,
  -- Stamped at resolution (+90 days, decision 131); consumed by the
  -- expiry job. frozen='S' (case in an authority's hands, decision 141)
  -- is never selected by the job.
  expires_at          DATETIME NULL,
  frozen              CHAR(1) NOT NULL DEFAULT 'N',
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted             CHAR(1) NOT NULL DEFAULT 'N',
  KEY idx_report_geo (lat, lng),
  KEY idx_report_created (created_at),
  KEY idx_report_reporter (reporter_account_id),
  CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_account_id)
    REFERENCES tb_user_account (id),
  -- Exactly one of category/free_tag (decision 9).
  CONSTRAINT chk_report_taxonomy CHECK ((category IS NULL) <> (free_tag IS NULL)),
  CONSTRAINT chk_report_status CHECK (status IN ('open', 'resolved'))
);

-- Append-only event trail (decision 19) — what the app renders as the
-- report's timeline. No update, no delete, no soft-delete column.
CREATE TABLE IF NOT EXISTS tb_report_timeline (
  id           BIGINT AUTO_INCREMENT PRIMARY KEY,
  tb_report_id INT NOT NULL,
  event_type   VARCHAR(30) NOT NULL,
  payload      JSON NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_timeline_report (tb_report_id, created_at),
  CONSTRAINT fk_timeline_report FOREIGN KEY (tb_report_id)
    REFERENCES tb_report (id)
);
