import { z } from 'zod'

/**
 * RateHelper body (decisions 182/183): `score` is the RatingScore of the
 * spec — an INTEGER 1..5 and nothing else (no text, no half stars);
 * `clientKey` is the rating's own idempotency key (UUID v4 generated by
 * the app, pattern of 137). Zod yields the per-field codes of decision 83
 * through parseBody.
 */
export const rateHelperDto = z.object({
  score: z.number().int().min(1).max(5),
  clientKey: z.string().uuid(),
})

export type RateHelperBody = z.infer<typeof rateHelperDto>
