import { z } from 'zod'

/**
 * PostMessage body (decisions 171/172/177). `clientKey` is the message's
 * own idempotency key (UUID v4 generated by the app, pattern of 137).
 * `text` is only type-checked here: trim, 1..CHAT_MAX_LENGTH and the
 * anti-contact rule live in the service, the single authority that reads
 * the env at call time.
 */
export const postChatMessageDto = z.object({
  clientKey: z.string().uuid(),
  text: z.string(),
})

/** Cursor paging (172): messages with id > after, ascending, 1..200. */
export const chatMessagesQueryDto = z.object({
  after: z.coerce.number().int().min(0).default(0),
  limit: z.coerce.number().int().min(1).max(200).default(50),
})

/** Panel read (C3, decision 175): cap of messages PER THREAD, 1..500,
 *  default 200 — the whole case is served in one audited request. */
export const chatEvidenceQueryDto = z.object({
  limit: z.coerce.number().int().min(1).max(500).default(200),
})
